# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.PositiveSmallIntegerField(choices=[(1, b'rest_framework.authentication.SessionAuthentication'), (2, b'rest_framework.authentication.BasicAuthentication')])),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FieldParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Field')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Char'), (2, b'Integer'), (3, b'Boolean'), (4, b'Decimal'), (5, b'Float'), (6, b'Foreign Key')])),
            ],
        ),
        migrations.CreateModel(
            name='FieldTypeParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='builder.FieldType')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='builder.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.PositiveSmallIntegerField(choices=[(1, b'rest_framework.permissions.AllowAny'), (2, b'rest_framework.permissions.IsAuthenticated'), (3, b'rest_framework.permissions.IsAdminUser'), (4, b'IsAuthenticatedOrReadOnly')])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('default_pagination_class', models.PositiveSmallIntegerField(choices=[(1, b'rest_framework.pagination.LimitOffsetPagination'), (2, b'rest_framework.pagination.PageNumberPagination'), (3, b'rest_framework.pagination.CursorPagination')])),
                ('page_size', models.PositiveSmallIntegerField(default=25)),
                ('db_engine', models.PositiveSmallIntegerField(choices=[(1, b'django.db.backends.sqlite3'), (2, b'django.db.backends.postgresql'), (3, b'django.db.backends.mysql'), (4, b'django.db.backends.oracle')])),
                ('default_authentication_class', models.ManyToManyField(to='builder.Authentication')),
                ('default_permissions_class', models.ManyToManyField(related_name='projects', to='builder.Permission')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.FieldType'),
        ),
        migrations.AddField(
            model_name='field',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='builder.Model'),
        ),
    ]
