# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_application_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
