# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 00:20
from __future__ import unicode_literals

from django.db import migrations

from ..constants import foChar, foInteger, foDecimal, foFloat, foBoolean, foForeignKey


def insert_field_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    FieldType = apps.get_model("builder", "FieldType")
    data = (
        (foChar,	'Char'),
        (foInteger,	'Integer'),
        (foInteger,	'PositiveSmallInteger'),
        (foBoolean, 'Boolean'),
        (foFloat, 'Float'),
        (foDecimal, 'Decimal'),
    )
    for type, name in data:
        FieldType.objects.get_or_create(name=name, type=type)


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20160514_0030'),
    ]

    operations = [
        migrations.RunPython(insert_field_types),
    ]
