# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 00:35
from __future__ import unicode_literals

from django.db import migrations


def insert_field_types_parameters(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    FieldType = apps.get_model("builder", "FieldType")
    FieldTypeParameter = apps.get_model("builder", "FieldTypeParameter")
    char_field = FieldType.objects.get(name='Char')
    data = (
        (char_field,	'null'),
        (char_field,	'blank'),
        (char_field,	'max_length'),
    )
    for field_type, name in data:
        FieldTypeParameter.objects.get_or_create(name=name, field_type=field_type)


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20160514_0020'),
    ]

    operations = [
        migrations.RunPython(insert_field_types_parameters),
    ]
